name: Deploy FastAPI with Nginx via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 100.64.85.36
          username: kali
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/Deployment/fastapi-book-project
            git pull origin main
            pip install -r requirements.txt

            # Restart Nginx
            sudo systemctl restart nginx

            # Restart Uvicorn (Ensure it’s killed before restarting)
            sudo pkill -f "uvicorn" || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > uvicorn.log 2>&1 &
