name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan 100.64.85.36 >> ~/.ssh/known_hosts
        shell: /usr/bin/bash -e {0}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Copy Files to Server
        run: |
          scp -i ~/.ssh/github_actions -r * kali@100.64.85.36:~/Deployment/fastapi-book-project

      - name: SSH into Server and Restart FastAPI
        run: |
          ssh -i ~/.ssh/github_actions kali@100.64.85.36 << 'EOF'
            cd ~/Deployment/fastapi-book-project
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
          EOF
